### ISSUE TITLE
Support Intercom v4 bindings

### ISSUE THREAD

**Issue by jamesgraham** [laravel-notification-channels/intercom#6]
We are unable to use this because other parts of our application use v4: https://github.com/intercom/intercom-php/releases/tag/v4.0.0

**Comment by ftw-soft** [comment]
Hi @jamesgraham 
I'll try to find some time in a couple of days to upgrade intercom to v4

**Comment by ftw-soft** [comment]
Hi @jamesgraham 
Released v1.2.0 with Intercom v4 support
